In [38]:
#(a)Maximum likelihood estimate and Inverse Hessian variance-covariance matrix
import numpy as np
import math
import scipy.optimize as opt
from scipy.stats import norm

c, k, w, r = np.loadtxt('MacroSeries.txt', delimiter=',', unpack=True)

def z_wk(w, k, alpha):
    z = np.log(w)-np.log(1-alpha)-alpha*np.log(k)
    return z

def normal_pdf(xvals, rho, mu, sigma):
    yvals = np.append(mu, xvals[0:99])
    mu_n = rho*yvals+(1-rho)*mu
    pdf_vals = np.exp(-(xvals-mu_n)**2/(2*sigma**2))/math.sqrt(2*math.pi*sigma**2)
    return pdf_vals

def log_lik_normal(xvals, rho, mu, sigma):
    pdf_vals = normal_pdf(xvals, rho, mu, sigma)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    return log_lik_val

def crit_normal_wk(params, *args):
    alpha, rho, mu, sigma = params
    w, k = args
    xvals = z_wk(w, k, alpha)
    log_lik_val = log_lik_normal(xvals, rho, mu, sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val


alpha_wk = 0.3
rho_wk = 0.9
mu_wk = 12
sigma_wk = 0.10

params_wk = np.array([alpha_wk, rho_wk, mu_wk, sigma_wk])
mle_args_wk = (w, k)
results_wk = opt.minimize(crit_normal_wk, params_wk, args=(mle_args_wk), method = 'L-BFGS-B', bounds=((1e-10,1-1e-10),(-1+1e-10,1-1e-10),(1e-10, None),(1e-10, None)))
alpha_wk_MLE, rho_wk_MLE, mu_wk_MLE, sigma_wk_MLE = results_wk.x

print('alpha_wk_MLE =', alpha_wk_MLE, 'rho_wk_MLE =', rho_wk_MLE, 'mu_wk_MLE =', mu_wk_MLE, ' sigma_wk_MLE =', sigma_wk_MLE)
print('Maximized-log-likelihood_wk: ', log_lik_normal(z_wk(w,k,alpha_wk_MLE), rho_wk_MLE, mu_wk_MLE, sigma_wk_MLE))
print("Hessian Matrix_wk = ")
print(results_wk.hess_inv*np.identity(4))

alpha_wk_MLE = 0.457520192833 rho_wk_MLE = 0.720486276524 mu_wk_MLE = 9.52266588754  sigma_wk_MLE = 0.0919961742613
Maximized-log-likelihood_wk:  96.7069080745
Hessian Matrix_wk = 
[[  3.88761660e-01   2.49851258e-02  -5.57999213e+00   3.30265272e-02]
 [  2.49851258e-02   1.62412719e-02  -3.32258593e-01  -5.88608171e-03]
 [ -5.57999213e+00  -3.32258593e-01   8.01760444e+01  -5.00435661e-01]
 [  3.30265272e-02  -5.88608171e-03  -5.00435661e-01   1.11373660e-02]]


In [39]:
#(b)Maximum likelihood estimate and Inverse Hessian variance-covariance matrix
def z_rk(r, k, alpha):
    z = np.log(r/(alpha*k**(alpha-1)))
    return z

def crit_normal_rk(params, *args):
    alpha, rho, mu, sigma = params
    r, k = args
    xvals = z_rk(r, k, alpha)
    log_lik_val = log_lik_normal(xvals, rho, mu, sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val


alpha_rk = 0.3
rho_rk = 0.9
mu_rk = 12
sigma_rk = 0.10

params_rk = np.array([alpha_rk, rho_rk, mu_rk, sigma_rk])
mle_args_rk = (r, k)
results_rk = opt.minimize(crit_normal_rk, params_rk, args=(mle_args_rk), method = 'L-BFGS-B', bounds=((1e-10,1-1e-10),(-1+1e-10,1-1e-10),(1e-10, None),(1e-10, None)))
alpha_rk_MLE, rho_rk_MLE, mu_rk_MLE, sigma_rk_MLE = results_rk.x

print('alpha_rk_MLE =', alpha_rk_MLE, 'rho_rk_MLE =', rho_rk_MLE, 'mu_rk_MLE =', mu_rk_MLE, ' sigma_rk_MLE =', sigma_rk_MLE)
print('Maximized-log-likelihood_rk: ', log_lik_normal(z_rk(r,k,alpha_rk_MLE), rho_rk_MLE, mu_rk_MLE, sigma_rk_MLE))
print("Hessian Matrix_rk = ")
print(results_rk.hess_inv*np.identity(4))

alpha_rk_MLE = 0.45744959632 rho_rk_MLE = 0.720523735243 mu_rk_MLE = 9.37149072605  sigma_rk_MLE = 0.0919973897798
Maximized-log-likelihood_rk:  96.7069079284
Hessian Matrix_rk = 
[[  5.74074867e+01  -1.02737738e+00  -1.02903560e+03  -1.32021523e+00]
 [ -1.02737738e+00   5.20253261e+00   1.86854351e+01   2.23042066e-01]
 [ -1.02903560e+03   1.86854351e+01   1.84455932e+04   2.36752344e+01]
 [ -1.32021523e+00   2.23042066e-01   2.36752344e+01   3.82243711e-02]]


In [40]:
#(c)Calculate the probability
k = 7500000
z_t_1 = 10
alpha = alpha_wk_MLE
z_opt = np.log(1/(alpha*k**(alpha-1)))
prob = 1 - norm.cdf(z_opt, rho_wk_MLE*z_t_1+(1-rho_wk_MLE)*mu_wk_MLE, sigma_wk_MLE)
print('z_opt=', z_opt)
print('probility=',prob)

z_opt= 9.36961396335
probility= 0.999999967052
